In [1]:
import numpy as np

In [2]:
#y_hat = sigmoid(np.dot(X,w1))

# define sigmoid function
def sigmoid(dot_product):
    output = 1/(1 + np.exp(-dot_product)) 
    return output

In [87]:
# the setup
np.random.seed(19)
y = np.array([0.2]) # output
X = np.array([2,2,3,3]) # input
w = np.random.rand(4,) # random weights vector
epochs = range(20) # epochs to train 
learning_rate = 2 # seems too high
length_of_X = range(len(X)) # for a range
n = len(X) # how many elements are there in X vector?
error_list = []

array([0.0975336 , 0.76124972, 0.24693797, 0.13813169])

In [82]:
for epoch in epochs:
# FEED FORWARD
    print('EPOCH: {}'.format(epoch))
    print('TARGET: {}'.format(y))
    
    # Predicting y
    y_hat = np.array(sigmoid(np.dot(X,w)))
    print('PREDICTION: {}'.format(y_hat))
    # Print weights
    #print('WEIGHTS: {}'.format(w))
    # How wrong is the prediction? 
    #It's not the mean squared error because we don't have multiple outputs
    se = np.power(np.subtract(y,y_hat),2)
    
    print('ERROR: {}'.format(se))
    error_list.append(se)
    # BACKPROPAGATION

    # Derivative calculation
    chain_1 = np.multiply(np.subtract(y,y_hat),2)
    #print('DERIVATIVE#1: {}'.format(chain_1))

    chain_2 = np.array(sigmoid(np.dot(X,w))*(1-sigmoid(np.dot(X,w))))
    #print('DERIVATIVE#2: {}'.format(chain_2))
  
    chain_3 = X # the derivative of a*x is a!
    #print('DERIVATIVE#3: {}'.format(chain_3))

    # DECLARING NEGATIVE GRADIENT (INCLUDING THE LEARNING RATE)
    neg_grad = -(chain_1*chain_2*chain_3)*learning_rate
    #print('NEGATIVE_GRADIENT: {}'.format(neg_grad))


    # UPDATING THE WEIGHTS 
    w = np.subtract(w,neg_grad)
    #print('WEIGHTS: {}'.format(w))
    print('-------')   

EPOCH: 0
TARGET: [0.2]
PREDICTION: 0.9948551702715747
ERROR: [0.63179474]
-------
EPOCH: 1
TARGET: [0.2]
PREDICTION: 0.9921666120700612
ERROR: [0.62752794]
-------
EPOCH: 2
TARGET: [0.2]
PREDICTION: 0.9852433529551735
ERROR: [0.61660712]
-------
EPOCH: 3
TARGET: [0.2]
PREDICTION: 0.9531969079253945
ERROR: [0.56730558]
-------
EPOCH: 4
TARGET: [0.2]
PREDICTION: 0.382077312797735
ERROR: [0.03315215]
-------
EPOCH: 5
TARGET: [0.2]
PREDICTION: 0.0070236036624337595
ERROR: [0.03723989]
-------
EPOCH: 6
TARGET: [0.2]
PREDICTION: 0.008070312782396487
ERROR: [0.036837]
-------
EPOCH: 7
TARGET: [0.2]
PREDICTION: 0.009455379900121706
ERROR: [0.03630725]
-------
EPOCH: 8
TARGET: [0.2]
PREDICTION: 0.011361830667911714
ERROR: [0.03558436]
-------
EPOCH: 9
TARGET: [0.2]
PREDICTION: 0.014123363437243497
ERROR: [0.03455012]
-------
EPOCH: 10
TARGET: [0.2]
PREDICTION: 0.01840537531554758
ERROR: [0.03297661]
-------
EPOCH: 11
TARGET: [0.2]
PREDICTION: 0.02569739297335753
ERROR: [0.0303814]
-------
EPOCH

In [83]:
error_list

[array([0.63179474]),
 array([0.62752794]),
 array([0.61660712]),
 array([0.56730558]),
 array([0.03315215]),
 array([0.03723989]),
 array([0.036837]),
 array([0.03630725]),
 array([0.03558436]),
 array([0.03455012]),
 array([0.03297661]),
 array([0.0303814]),
 array([0.02564198]),
 array([0.01617178]),
 array([0.00152201]),
 array([0.00242079]),
 array([0.00756554]),
 array([0.00158897]),
 array([0.00503261]),
 array([0.00286265])]